services:
  caddy:
    image: caddy:2
    container_name: caddy
    restart: always
    ports:
      - 80:80  # Needed for the ACME HTTP-01 challenge.
      - 443:443
    volumes:
      - ./caddy-config:/etc/caddy/
      - ../../caddy-data:/data
      - ../../static-content:/static
    networks:
      - sharednetwork

networks:
  sharednetwork:
    external: true